# Site settings
title: Writing with Digital Technologies
description: "A resource for Writing with Digital Technologies Students"
url: "https://kristinashirk.github.io/digital-tech/#"
author:
  name: "Kristina Shirk"
  email: "shirk019@umn.edu"
  url: "https://github.com/kristinashirk"

# Build settings
baseurl: /digital-tech/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
